version: '3.8'

services:
  wppconnect-server:
    container_name: wppconnect-server
    build: .
    ports:
      - '3010:3010'
    environment:
      - PORT=3010
      - SECRET_KEY=defaultsecret
    networks:
      - sirio-net
    restart: unless-stopped

networks:
  sirio-net:
    external: true
